// Code generated by ent, DO NOT EDIT.

package example

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/axiomod/axiomod/platform/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Example {
	return predicate.Example(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Example {
	return predicate.Example(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Example {
	return predicate.Example(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Example {
	return predicate.Example(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Example {
	return predicate.Example(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Example {
	return predicate.Example(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Example {
	return predicate.Example(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Example {
	return predicate.Example(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Example {
	return predicate.Example(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldDescription, v))
}

// ValueType applies equality check predicate on the "value_type" field. It's identical to ValueTypeEQ.
func ValueType(v string) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldValueType, v))
}

// ValueCount applies equality check predicate on the "value_count" field. It's identical to ValueCountEQ.
func ValueCount(v int) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldValueCount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Example {
	return predicate.Example(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Example {
	return predicate.Example(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Example {
	return predicate.Example(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Example {
	return predicate.Example(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Example {
	return predicate.Example(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Example {
	return predicate.Example(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Example {
	return predicate.Example(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Example {
	return predicate.Example(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Example {
	return predicate.Example(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Example {
	return predicate.Example(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Example {
	return predicate.Example(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Example {
	return predicate.Example(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Example {
	return predicate.Example(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Example {
	return predicate.Example(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Example {
	return predicate.Example(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Example {
	return predicate.Example(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Example {
	return predicate.Example(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Example {
	return predicate.Example(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Example {
	return predicate.Example(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Example {
	return predicate.Example(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Example {
	return predicate.Example(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Example {
	return predicate.Example(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Example {
	return predicate.Example(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Example {
	return predicate.Example(sql.FieldContainsFold(FieldDescription, v))
}

// ValueTypeEQ applies the EQ predicate on the "value_type" field.
func ValueTypeEQ(v string) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldValueType, v))
}

// ValueTypeNEQ applies the NEQ predicate on the "value_type" field.
func ValueTypeNEQ(v string) predicate.Example {
	return predicate.Example(sql.FieldNEQ(FieldValueType, v))
}

// ValueTypeIn applies the In predicate on the "value_type" field.
func ValueTypeIn(vs ...string) predicate.Example {
	return predicate.Example(sql.FieldIn(FieldValueType, vs...))
}

// ValueTypeNotIn applies the NotIn predicate on the "value_type" field.
func ValueTypeNotIn(vs ...string) predicate.Example {
	return predicate.Example(sql.FieldNotIn(FieldValueType, vs...))
}

// ValueTypeGT applies the GT predicate on the "value_type" field.
func ValueTypeGT(v string) predicate.Example {
	return predicate.Example(sql.FieldGT(FieldValueType, v))
}

// ValueTypeGTE applies the GTE predicate on the "value_type" field.
func ValueTypeGTE(v string) predicate.Example {
	return predicate.Example(sql.FieldGTE(FieldValueType, v))
}

// ValueTypeLT applies the LT predicate on the "value_type" field.
func ValueTypeLT(v string) predicate.Example {
	return predicate.Example(sql.FieldLT(FieldValueType, v))
}

// ValueTypeLTE applies the LTE predicate on the "value_type" field.
func ValueTypeLTE(v string) predicate.Example {
	return predicate.Example(sql.FieldLTE(FieldValueType, v))
}

// ValueTypeContains applies the Contains predicate on the "value_type" field.
func ValueTypeContains(v string) predicate.Example {
	return predicate.Example(sql.FieldContains(FieldValueType, v))
}

// ValueTypeHasPrefix applies the HasPrefix predicate on the "value_type" field.
func ValueTypeHasPrefix(v string) predicate.Example {
	return predicate.Example(sql.FieldHasPrefix(FieldValueType, v))
}

// ValueTypeHasSuffix applies the HasSuffix predicate on the "value_type" field.
func ValueTypeHasSuffix(v string) predicate.Example {
	return predicate.Example(sql.FieldHasSuffix(FieldValueType, v))
}

// ValueTypeEqualFold applies the EqualFold predicate on the "value_type" field.
func ValueTypeEqualFold(v string) predicate.Example {
	return predicate.Example(sql.FieldEqualFold(FieldValueType, v))
}

// ValueTypeContainsFold applies the ContainsFold predicate on the "value_type" field.
func ValueTypeContainsFold(v string) predicate.Example {
	return predicate.Example(sql.FieldContainsFold(FieldValueType, v))
}

// ValueCountEQ applies the EQ predicate on the "value_count" field.
func ValueCountEQ(v int) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldValueCount, v))
}

// ValueCountNEQ applies the NEQ predicate on the "value_count" field.
func ValueCountNEQ(v int) predicate.Example {
	return predicate.Example(sql.FieldNEQ(FieldValueCount, v))
}

// ValueCountIn applies the In predicate on the "value_count" field.
func ValueCountIn(vs ...int) predicate.Example {
	return predicate.Example(sql.FieldIn(FieldValueCount, vs...))
}

// ValueCountNotIn applies the NotIn predicate on the "value_count" field.
func ValueCountNotIn(vs ...int) predicate.Example {
	return predicate.Example(sql.FieldNotIn(FieldValueCount, vs...))
}

// ValueCountGT applies the GT predicate on the "value_count" field.
func ValueCountGT(v int) predicate.Example {
	return predicate.Example(sql.FieldGT(FieldValueCount, v))
}

// ValueCountGTE applies the GTE predicate on the "value_count" field.
func ValueCountGTE(v int) predicate.Example {
	return predicate.Example(sql.FieldGTE(FieldValueCount, v))
}

// ValueCountLT applies the LT predicate on the "value_count" field.
func ValueCountLT(v int) predicate.Example {
	return predicate.Example(sql.FieldLT(FieldValueCount, v))
}

// ValueCountLTE applies the LTE predicate on the "value_count" field.
func ValueCountLTE(v int) predicate.Example {
	return predicate.Example(sql.FieldLTE(FieldValueCount, v))
}

// ValueTagsIsNil applies the IsNil predicate on the "value_tags" field.
func ValueTagsIsNil() predicate.Example {
	return predicate.Example(sql.FieldIsNull(FieldValueTags))
}

// ValueTagsNotNil applies the NotNil predicate on the "value_tags" field.
func ValueTagsNotNil() predicate.Example {
	return predicate.Example(sql.FieldNotNull(FieldValueTags))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Example {
	return predicate.Example(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Example {
	return predicate.Example(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Example {
	return predicate.Example(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Example {
	return predicate.Example(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Example {
	return predicate.Example(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Example) predicate.Example {
	return predicate.Example(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Example) predicate.Example {
	return predicate.Example(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Example) predicate.Example {
	return predicate.Example(sql.NotPredicates(p))
}
