// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/axiomod/axiomod/platform/ent/example"
)

// ExampleCreate is the builder for creating a Example entity.
type ExampleCreate struct {
	config
	mutation *ExampleMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ExampleCreate) SetName(v string) *ExampleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ExampleCreate) SetDescription(v string) *ExampleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetValueType sets the "value_type" field.
func (_c *ExampleCreate) SetValueType(v string) *ExampleCreate {
	_c.mutation.SetValueType(v)
	return _c
}

// SetNillableValueType sets the "value_type" field if the given value is not nil.
func (_c *ExampleCreate) SetNillableValueType(v *string) *ExampleCreate {
	if v != nil {
		_c.SetValueType(*v)
	}
	return _c
}

// SetValueCount sets the "value_count" field.
func (_c *ExampleCreate) SetValueCount(v int) *ExampleCreate {
	_c.mutation.SetValueCount(v)
	return _c
}

// SetNillableValueCount sets the "value_count" field if the given value is not nil.
func (_c *ExampleCreate) SetNillableValueCount(v *int) *ExampleCreate {
	if v != nil {
		_c.SetValueCount(*v)
	}
	return _c
}

// SetValueTags sets the "value_tags" field.
func (_c *ExampleCreate) SetValueTags(v []string) *ExampleCreate {
	_c.mutation.SetValueTags(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExampleCreate) SetCreatedAt(v time.Time) *ExampleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExampleCreate) SetNillableCreatedAt(v *time.Time) *ExampleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExampleCreate) SetUpdatedAt(v time.Time) *ExampleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExampleCreate) SetNillableUpdatedAt(v *time.Time) *ExampleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExampleCreate) SetID(v string) *ExampleCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ExampleMutation object of the builder.
func (_c *ExampleCreate) Mutation() *ExampleMutation {
	return _c.mutation
}

// Save creates the Example in the database.
func (_c *ExampleCreate) Save(ctx context.Context) (*Example, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExampleCreate) SaveX(ctx context.Context) *Example {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExampleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExampleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExampleCreate) defaults() {
	if _, ok := _c.mutation.ValueType(); !ok {
		v := example.DefaultValueType
		_c.mutation.SetValueType(v)
	}
	if _, ok := _c.mutation.ValueCount(); !ok {
		v := example.DefaultValueCount
		_c.mutation.SetValueCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := example.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := example.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExampleCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Example.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := example.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Example.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Example.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := example.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Example.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ValueType(); !ok {
		return &ValidationError{Name: "value_type", err: errors.New(`ent: missing required field "Example.value_type"`)}
	}
	if _, ok := _c.mutation.ValueCount(); !ok {
		return &ValidationError{Name: "value_count", err: errors.New(`ent: missing required field "Example.value_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Example.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Example.updated_at"`)}
	}
	return nil
}

func (_c *ExampleCreate) sqlSave(ctx context.Context) (*Example, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Example.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExampleCreate) createSpec() (*Example, *sqlgraph.CreateSpec) {
	var (
		_node = &Example{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(example.Table, sqlgraph.NewFieldSpec(example.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(example.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(example.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ValueType(); ok {
		_spec.SetField(example.FieldValueType, field.TypeString, value)
		_node.ValueType = value
	}
	if value, ok := _c.mutation.ValueCount(); ok {
		_spec.SetField(example.FieldValueCount, field.TypeInt, value)
		_node.ValueCount = value
	}
	if value, ok := _c.mutation.ValueTags(); ok {
		_spec.SetField(example.FieldValueTags, field.TypeJSON, value)
		_node.ValueTags = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(example.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(example.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ExampleCreateBulk is the builder for creating many Example entities in bulk.
type ExampleCreateBulk struct {
	config
	err      error
	builders []*ExampleCreate
}

// Save creates the Example entities in the database.
func (_c *ExampleCreateBulk) Save(ctx context.Context) ([]*Example, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Example, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExampleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExampleCreateBulk) SaveX(ctx context.Context) []*Example {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExampleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExampleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
