// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/axiomod/axiomod/platform/ent/example"
	"github.com/axiomod/axiomod/platform/ent/predicate"
)

// ExampleUpdate is the builder for updating Example entities.
type ExampleUpdate struct {
	config
	hooks    []Hook
	mutation *ExampleMutation
}

// Where appends a list predicates to the ExampleUpdate builder.
func (_u *ExampleUpdate) Where(ps ...predicate.Example) *ExampleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ExampleUpdate) SetName(v string) *ExampleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ExampleUpdate) SetNillableName(v *string) *ExampleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExampleUpdate) SetDescription(v string) *ExampleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExampleUpdate) SetNillableDescription(v *string) *ExampleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetValueType sets the "value_type" field.
func (_u *ExampleUpdate) SetValueType(v string) *ExampleUpdate {
	_u.mutation.SetValueType(v)
	return _u
}

// SetNillableValueType sets the "value_type" field if the given value is not nil.
func (_u *ExampleUpdate) SetNillableValueType(v *string) *ExampleUpdate {
	if v != nil {
		_u.SetValueType(*v)
	}
	return _u
}

// SetValueCount sets the "value_count" field.
func (_u *ExampleUpdate) SetValueCount(v int) *ExampleUpdate {
	_u.mutation.ResetValueCount()
	_u.mutation.SetValueCount(v)
	return _u
}

// SetNillableValueCount sets the "value_count" field if the given value is not nil.
func (_u *ExampleUpdate) SetNillableValueCount(v *int) *ExampleUpdate {
	if v != nil {
		_u.SetValueCount(*v)
	}
	return _u
}

// AddValueCount adds value to the "value_count" field.
func (_u *ExampleUpdate) AddValueCount(v int) *ExampleUpdate {
	_u.mutation.AddValueCount(v)
	return _u
}

// SetValueTags sets the "value_tags" field.
func (_u *ExampleUpdate) SetValueTags(v []string) *ExampleUpdate {
	_u.mutation.SetValueTags(v)
	return _u
}

// AppendValueTags appends value to the "value_tags" field.
func (_u *ExampleUpdate) AppendValueTags(v []string) *ExampleUpdate {
	_u.mutation.AppendValueTags(v)
	return _u
}

// ClearValueTags clears the value of the "value_tags" field.
func (_u *ExampleUpdate) ClearValueTags() *ExampleUpdate {
	_u.mutation.ClearValueTags()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExampleUpdate) SetUpdatedAt(v time.Time) *ExampleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExampleMutation object of the builder.
func (_u *ExampleUpdate) Mutation() *ExampleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ExampleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExampleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ExampleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExampleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExampleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := example.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExampleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := example.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Example.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := example.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Example.description": %w`, err)}
		}
	}
	return nil
}

func (_u *ExampleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(example.Table, example.Columns, sqlgraph.NewFieldSpec(example.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(example.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(example.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueType(); ok {
		_spec.SetField(example.FieldValueType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueCount(); ok {
		_spec.SetField(example.FieldValueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValueCount(); ok {
		_spec.AddField(example.FieldValueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValueTags(); ok {
		_spec.SetField(example.FieldValueTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValueTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, example.FieldValueTags, value)
		})
	}
	if _u.mutation.ValueTagsCleared() {
		_spec.ClearField(example.FieldValueTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(example.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{example.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ExampleUpdateOne is the builder for updating a single Example entity.
type ExampleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExampleMutation
}

// SetName sets the "name" field.
func (_u *ExampleUpdateOne) SetName(v string) *ExampleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ExampleUpdateOne) SetNillableName(v *string) *ExampleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ExampleUpdateOne) SetDescription(v string) *ExampleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ExampleUpdateOne) SetNillableDescription(v *string) *ExampleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetValueType sets the "value_type" field.
func (_u *ExampleUpdateOne) SetValueType(v string) *ExampleUpdateOne {
	_u.mutation.SetValueType(v)
	return _u
}

// SetNillableValueType sets the "value_type" field if the given value is not nil.
func (_u *ExampleUpdateOne) SetNillableValueType(v *string) *ExampleUpdateOne {
	if v != nil {
		_u.SetValueType(*v)
	}
	return _u
}

// SetValueCount sets the "value_count" field.
func (_u *ExampleUpdateOne) SetValueCount(v int) *ExampleUpdateOne {
	_u.mutation.ResetValueCount()
	_u.mutation.SetValueCount(v)
	return _u
}

// SetNillableValueCount sets the "value_count" field if the given value is not nil.
func (_u *ExampleUpdateOne) SetNillableValueCount(v *int) *ExampleUpdateOne {
	if v != nil {
		_u.SetValueCount(*v)
	}
	return _u
}

// AddValueCount adds value to the "value_count" field.
func (_u *ExampleUpdateOne) AddValueCount(v int) *ExampleUpdateOne {
	_u.mutation.AddValueCount(v)
	return _u
}

// SetValueTags sets the "value_tags" field.
func (_u *ExampleUpdateOne) SetValueTags(v []string) *ExampleUpdateOne {
	_u.mutation.SetValueTags(v)
	return _u
}

// AppendValueTags appends value to the "value_tags" field.
func (_u *ExampleUpdateOne) AppendValueTags(v []string) *ExampleUpdateOne {
	_u.mutation.AppendValueTags(v)
	return _u
}

// ClearValueTags clears the value of the "value_tags" field.
func (_u *ExampleUpdateOne) ClearValueTags() *ExampleUpdateOne {
	_u.mutation.ClearValueTags()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ExampleUpdateOne) SetUpdatedAt(v time.Time) *ExampleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ExampleMutation object of the builder.
func (_u *ExampleUpdateOne) Mutation() *ExampleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ExampleUpdate builder.
func (_u *ExampleUpdateOne) Where(ps ...predicate.Example) *ExampleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ExampleUpdateOne) Select(field string, fields ...string) *ExampleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Example entity.
func (_u *ExampleUpdateOne) Save(ctx context.Context) (*Example, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ExampleUpdateOne) SaveX(ctx context.Context) *Example {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ExampleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ExampleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ExampleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := example.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ExampleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := example.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Example.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := example.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Example.description": %w`, err)}
		}
	}
	return nil
}

func (_u *ExampleUpdateOne) sqlSave(ctx context.Context) (_node *Example, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(example.Table, example.Columns, sqlgraph.NewFieldSpec(example.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Example.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, example.FieldID)
		for _, f := range fields {
			if !example.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != example.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(example.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(example.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueType(); ok {
		_spec.SetField(example.FieldValueType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValueCount(); ok {
		_spec.SetField(example.FieldValueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValueCount(); ok {
		_spec.AddField(example.FieldValueCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ValueTags(); ok {
		_spec.SetField(example.FieldValueTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedValueTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, example.FieldValueTags, value)
		})
	}
	if _u.mutation.ValueTagsCleared() {
		_spec.ClearField(example.FieldValueTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(example.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Example{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{example.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
