// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/axiomod/axiomod/platform/ent/example"
	"github.com/axiomod/axiomod/platform/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	exampleFields := schema.Example{}.Fields()
	_ = exampleFields
	// exampleDescName is the schema descriptor for name field.
	exampleDescName := exampleFields[1].Descriptor()
	// example.NameValidator is a validator for the "name" field. It is called by the builders before save.
	example.NameValidator = exampleDescName.Validators[0].(func(string) error)
	// exampleDescDescription is the schema descriptor for description field.
	exampleDescDescription := exampleFields[2].Descriptor()
	// example.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	example.DescriptionValidator = exampleDescDescription.Validators[0].(func(string) error)
	// exampleDescValueType is the schema descriptor for value_type field.
	exampleDescValueType := exampleFields[3].Descriptor()
	// example.DefaultValueType holds the default value on creation for the value_type field.
	example.DefaultValueType = exampleDescValueType.Default.(string)
	// exampleDescValueCount is the schema descriptor for value_count field.
	exampleDescValueCount := exampleFields[4].Descriptor()
	// example.DefaultValueCount holds the default value on creation for the value_count field.
	example.DefaultValueCount = exampleDescValueCount.Default.(int)
	// exampleDescCreatedAt is the schema descriptor for created_at field.
	exampleDescCreatedAt := exampleFields[6].Descriptor()
	// example.DefaultCreatedAt holds the default value on creation for the created_at field.
	example.DefaultCreatedAt = exampleDescCreatedAt.Default.(func() time.Time)
	// exampleDescUpdatedAt is the schema descriptor for updated_at field.
	exampleDescUpdatedAt := exampleFields[7].Descriptor()
	// example.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	example.DefaultUpdatedAt = exampleDescUpdatedAt.Default.(func() time.Time)
	// example.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	example.UpdateDefaultUpdatedAt = exampleDescUpdatedAt.UpdateDefault.(func() time.Time)
}
