// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExamplesColumns holds the columns for the "examples" table.
	ExamplesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
		{Name: "value_type", Type: field.TypeString, Default: ""},
		{Name: "value_count", Type: field.TypeInt, Default: 0},
		{Name: "value_tags", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ExamplesTable holds the schema information for the "examples" table.
	ExamplesTable = &schema.Table{
		Name:       "examples",
		Columns:    ExamplesColumns,
		PrimaryKey: []*schema.Column{ExamplesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExamplesTable,
	}
)

func init() {
}
